sudo: required

language: cpp

git:
    depth: 1

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "dkQzxuKiFCzMS0BCwJujjsA2ztk4ppnfpyIX0cGqnVm3H+aTgTo210dLKxUdkG7bt/Gp6iYl9g+1DxT12+XiSohswSMvpl91RDqG3Sirlukf2+tmjmY1i4jNrX9vbCszUFNHTmCsG/6x+JJhcQuJmJrNAc6Nqgo/309k8sqyVxRZj90IBdUrfZbifawn96VwkD1y1SNqzEk61HgVPVBMyx/bK3yv6rBgHOHeoYjDw9Eg4D/9GjkgkRVYqYzKRRiTSDLXJ3xN3E6ouWVME1iglKhrur6d31z30Dmro8LYcmP0bqBN9A/h2Axk5Ga+7W+E60w5LrPmYDQ91N9IEi+nSWXooMDNfUOSRJ5dYQGgd2vj208u/WirLnzUNax9LocecTm65Kj7lLrPyUrArLBf6kN8hODSNdxK8Ci4mcGC6Fa+mwMaDTVkPv85sueGquTMbYwtJkhY/ylYXNdzcjCvCUbrZVyPcUNcDIlZf504cBPMsUCarngWsFm8zp+lK3YQs2KA4Dn7IZgCgOJ+Kyk8pT3vgAPUy8Fs0GNM7LZMUNzD/oDo+rQt91HMI1/OX0L6GY53xeClA8oHPQteGcqd7ADC1GQ/hg4EYzg30vlwEy71TpNBhmgbjwgSm2luyfO0qdI6Y7wVPlzhKLl48AL0JmR5ydnWxK0WaCyW21rwlNw="
    - COVERITY_SCAN_PROJECT_NAME="pjasicek/CaptainClaw"
    - COVERITY_SCAN_BRANCH_PATTERN="master"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="pjasicek@gmail.com"
    - COVERITY_SCAN_BUILD_COMMAND="make -j 4"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="mkdir build; cd build; cmake .."

matrix:
  include:
    - os: linux
      dist: trusty
      name: "Linux clang"
      compiler: clang
      env: PLATFORM=linux
    - os: linux
      dist: trusty
      name: "Linux gcc"
      compiler: gcc
      env: PLATFORM=linux
    - os: linux
      dist: trusty
      name: "Android"
      compiler: gcc
      env: PLATFORM=android CMAKE_ARGS="-DAndroid=1 -DCMAKE_TOOLCHAIN_FILE=../Android.cmake -Dtools=$HOME/android-toolchain/"
    - os: osx
      compiler: clang
      name: "macOS"
      env: PLATFORM=osx
    - os: windows
      name: "Windows"
      env: PLATFORM=windows
    - os: linux
      dist: xenial
      name: "Emscripten"
      compiler: clang
      env: PLATFORM=emscripten CMAKE_ARGS="-DEmscripten=1" CMAKE_EXECUTOR=emcmake

script:
    "./travis.sh"
